# pane navigation & resizing

# move current window to session index (0 -> 10)
run-shell -b 'for i in 1 2 3 4 5 6 7 8 9; do tmux bind "$i" run-shell "~/.config/tmux/scripts/move_window_to_session.sh $i"; done; tmux bind 0 run-shell "~/.config/tmux/scripts/move_window_to_session.sh 10"'

is_vim='ps -o state= -o comm= -t "#{pane_tty}" | grep -iqE "^[^TXZ ]+ +((\\S+/)?g?(view|l?n?vim?x?|fzf)(diff)?)$"'

bind -n M-h if-shell "$is_vim" 'send-keys M-h' 'run-shell "~/.config/tmux/scripts/pane/smart_focus.sh left"'
bind -n M-j if-shell "$is_vim" 'send-keys M-j' 'run-shell "~/.config/tmux/scripts/pane/smart_focus.sh down"'
bind -n M-k if-shell "$is_vim" 'send-keys M-k' 'run-shell "~/.config/tmux/scripts/pane/smart_focus.sh up"'
bind -n M-l if-shell "$is_vim" 'send-keys M-l' 'run-shell "~/.config/tmux/scripts/pane/smart_focus.sh right"'
bind > swap-pane -D
bind < swap-pane -U
bind | swap-pane
bind Space run-shell "~/.config/tmux/scripts/toggle_orientation.sh"

bind W choose-tree -Z
bind S choose-tree 'move-pane -v -s "%%"'
bind V choose-tree 'move-pane -h -s "%%"'

bind -n M-H resize-pane -L 3
bind -n M-J resize-pane -D 3
bind -n M-K resize-pane -U 3
bind -n M-L resize-pane -R 3

bind -n M-\\ if-shell "$is_vim" 'send-keys M-\\' 'select-pane -l'
