# sync input toggle
bind C-g if-shell '[[ $(tmux showw synchronize-panes | cut -d\  -f2) == "on" ]]' \
'setw synchronize-panes off; set -g pane-border-style fg=#{?#{!=:#{environ:TMUX_THEME_COLOR},},#{environ:TMUX_THEME_COLOR},#b294bb}' \
'setw synchronize-panes on; set -g pane-border-style fg=red'

# local mac theme
run-shell "~/.config/tmux/scripts/update_theme_color.sh"
setw -g pane-border-status off
set -g pane-border-style fg=colour244

set -g status-style "bg=#222437,fg=#c5c8c6"
set -g status-justify 'left'
set -g status-left-length 56
set -g status-right-length 150
set -g status-interval 30

set -g @tab_bg "#222437"
set -g @tab_text "#cdd6f4"
set -g @tab_subtext "#a6adc8"
set -g @tab_overlay "#6c7086"
set -g @tab_active_bg "#7A5CFA"
set -g @tab_copy_fg "black"
set -g @tab_copy_bg "yellow"
set -g @status_fg "#6C7086"
set -g @time_fg "#FFF8F2"
set -g @time_bg "#245C69"
set -g @date_fg "#FFF8F2"
set -g @date_bg "#6B4862"
set -g @pane_flag_fg "#FFF8F2"
set -g @pane_flag_bg "#70543C"
set -g @session_label_fg "#FFF8F2"
set -g @session_label_bg "#3F4C6B"
set -g @things_fg "#F7F9FC"
set -g @things_icon_fg "#FFD166"
set -g @things_bg "#3A73A8"

setw -g window-status-separator ''
set -g window-status-style "bg=#222437"
set -g window-status-current-style "fg=#{?pane_in_mode,#{@tab_copy_fg},#ffffff},bg=#{?pane_in_mode,#{@tab_copy_bg},#{@tab_active_bg}}"
set -g window-status-last-style 'fg=#{@tab_text},bg=#{@tab_bg}'
setw -g window-status-format '#[fg=#{@tab_overlay},bg=#{@tab_bg}] #I:#[fg=#{@tab_subtext}]#{=10:#{window_name}} #[fg=#3a414b,bg=#{@tab_bg}]│#[default] '
setw -g window-status-current-format '#[fg=#{?pane_in_mode,#{@tab_copy_fg},#ffffff},bg=#{?pane_in_mode,#{@tab_copy_bg},#{@tab_active_bg}}]#[bold] #I: #{=10:#{window_name}}#{?window_zoomed_flag, #[bold]Z,} #[fg=#{?pane_in_mode,#{@tab_copy_bg},#{@tab_active_bg}},bg=#{@tab_bg},nobold]#[default]'

setw -g window-status-activity-style "fg=#f9e2af,bold"
setw -g window-status-bell-style "fg=#ff5555,bold"
set-environment -g TMUX_THINGS 1
set-environment -g TMUX_THINGS_MIN_WIDTH 130
set-environment -g TMUX_THINGS_REFRESH_SEC 60
set-environment -g TMUX_THINGS_LIST_NAME "今天"
set-environment -g TMUX_THINGS_PILL_WIDTH 28
# session icon mapping by numeric prefix (1-based)
set-environment -g TMUX_SESSION_ICONS "󰼏,󰼐,󰼑,󰼒,󰼓,󰼔,󰼕,󰼖,󰼗,󰿪"
set-option -g status-left ""
set-option -g status-right "#(~/.config/tmux/tmux-status/right.sh)"

unbind t
unbind T
